---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: traefik-system
spec:
  interval: 15m
  url: https://helm.traefik.io/traefik
  timeout: 3m